logLevel=INFO
reloadOnChange=true
enableWelcomeMessage=false
mailboxLimit=20
maxSubjectLength=25
maxBodyLength=2500
maxPlayerAttachments=5
sendCooldownSeconds=30
attachmentExpiryDays=30
recentPlayerDays=30
enableAnnouncements=true
enableCod=false
discordAuditChannelId=0
enableExtraMailboxShopOffer=true
extraMailboxBasePrice=1000
extraMailboxPriceIncreaseFactor=1
trustedPluginSenders=OZ - Marketplace
